name: Modcraft-Plugin
main: io.github.black_Kittys22.modcraft.Modcraft
version: 2.0.0
api-version: "1.21"  # WICHTIG!

author: black_Kittys
description: Ein Plugin für den Modcraft Server

libraries:
  - "de.miraculixx:kpaper:1.1.2"
  - "dev.jorel:commandapi-bukkit-shade:10.0.0"
  - "dev.jorel:commandapi-bukkit-kotlin:10.0.0"
  - "org.reflections:reflections:0.10.2"
  - "net.kyori:adventure-api:4.17.0"
  - "net.kyori:adventure-platform-bukkit:4.3.0"